# Generated by Django 3.0.8 on 2022-08-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('attribute', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.CharField(max_length=20)),
                ('mbti', models.CharField(max_length=5)),
                ('cocktail_img', models.URLField()),
                ('desc', models.TextField()),
                ('fit_cocktail', models.CharField(max_length=20)),
                ('fit_cocktail_url', models.URLField()),
                ('unfit_cocktail', models.CharField(max_length=20)),
                ('unfit_cocktail_url', models.URLField()),
            ],
        ),
    ]
