# Generated by Django 3.0.8 on 2022-08-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='cocktail_img',
            new_name='cocktail_url',
        ),
    ]
