# Generated by Django 3.0.8 on 2022-03-26 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('eng_name', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('img_color', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('recipe', models.TextField()),
                ('ohzu_point', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Base')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='bases',
            field=models.ManyToManyField(through='main.Cocktail_Base', to='main.Base'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='flavors',
            field=models.ManyToManyField(to='main.Flavor'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='main.Cocktail_Ingredient', to='main.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='moods',
            field=models.ManyToManyField(to='main.Mood'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ornaments',
            field=models.ManyToManyField(to='main.Ornament'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='weathers',
            field=models.ManyToManyField(to='main.Weather'),
        ),
    ]
