# Generated by Django 3.0.8 on 2022-03-26 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='img_color',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='color',
            new_name='cocktail_color',
        ),
    ]
