# Generated by Django 3.0.8 on 2022-03-28 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('eng_name', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('background_color', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('cocktail_color', models.CharField(max_length=10)),
                ('recipe', models.TextField()),
                ('ohzu_point', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Weather')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Ornament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('ornament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ornament')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('mood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Mood')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Flavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=20)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Base')),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cocktail')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='bases',
            field=models.ManyToManyField(through='main.Cocktail_Base', to='main.Base'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='flavors',
            field=models.ManyToManyField(through='main.Cocktail_Flavor', to='main.Flavor'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='main.Cocktail_Ingredient', to='main.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='moods',
            field=models.ManyToManyField(through='main.Cocktail_Mood', to='main.Mood'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ornaments',
            field=models.ManyToManyField(through='main.Cocktail_Ornament', to='main.Ornament'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='weathers',
            field=models.ManyToManyField(through='main.Cocktail_Weather', to='main.Weather'),
        ),
    ]
