# Generated by Django 3.0.8 on 2022-03-22 14:55

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='base',
            field=taggit.managers.TaggableManager(help_text='List all the available base tags here.', through='main.ThroughBaseTag', to='main.BaseTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='flavor',
            field=taggit.managers.TaggableManager(help_text='List all the available flavor tags here.', through='main.ThroughFlavorTag', to='main.FlavorTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients_rec',
            field=taggit.managers.TaggableManager(blank=True, help_text='List all the available ingredients_rec tags here.', through='main.ThroughIngredientsRecTag', to='main.IngredientsRecTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='mood',
            field=taggit.managers.TaggableManager(help_text='List all the available mood tags here.', through='main.ThroughMoodTag', to='main.MoodTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ornament',
            field=taggit.managers.TaggableManager(help_text='List all the available ornament tags here.', through='main.ThroughOrnamentTag', to='main.OrnamentTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='weather_and_season',
            field=taggit.managers.TaggableManager(help_text='List all the available weather and season tags here.', through='main.ThroughWeatherSeasonTag', to='main.WeatherSeasonTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
