# Generated by Django 3.0.8 on 2022-04-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ohzu_point',
            field=models.TextField(blank=True),
        ),
    ]
