# Generated by Django 3.0.8 on 2022-04-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220404_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='flavor',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flavor',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mood',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ornament',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='tag_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
