# Generated by Django 3.0.8 on 2022-06-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20220409_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='flavor',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='mood',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='ornament',
            name='img',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='weather',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
