# Generated by Django 3.0.8 on 2022-06-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_base_img2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='img2',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='img2',
            field=models.URLField(blank=True),
        ),
    ]
