# Generated by Django 3.0.8 on 2022-07-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ingredient_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='img3',
            field=models.URLField(blank=True),
        ),
    ]
