# Generated by Django 3.0.8 on 2022-08-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_cocktail_img3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='img4',
            field=models.URLField(blank=True),
        ),
    ]
